-- Call list + outbound tables (previously created ad hoc; now tracked) + campaign columns

create table if not exists call_contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  first_name text,
  last_name text,
  firm text,
  position text,
  dept text,
  email text,
  phone text,
  linkedin text,
  confidence int,
  priority text,
  created_at timestamptz not null default now()
);

create table if not exists call_activities (
  id bigint generated by default as identity primary key,
  contact_id bigint,
  contact_name text,
  firm text,
  disposition text,
  notes text,
  block_type text,
  session_id text,
  duration_secs int default 0,
  created_at timestamptz not null default now()
);

-- Campaign enrichment columns (idempotent)
alter table call_contacts add column if not exists phone_type text default 'unknown';
alter table call_contacts add column if not exists phone_status text default 'none';
alter table call_contacts add column if not exists dnc boolean not null default false;
alter table call_contacts add column if not exists timezone text default 'ET';
alter table call_contacts add column if not exists group_name text;

create index if not exists idx_call_contacts_group on call_contacts(group_name);
create index if not exists idx_call_contacts_tz on call_contacts(timezone);

alter table call_contacts enable row level security;
alter table call_activities enable row level security;

do $$ begin
  create policy "Authenticated full access" on call_contacts for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Authenticated full access" on call_activities for all to authenticated using (true) with check (true);
exception when duplicate_object then null; end $$;
